version: '3'

services:
  # nombre del servicio
  mariadb: 
    # imagen a utilizar
    image: mariadb:10.6.14
    restart: always

    # nombre del contenedor
    container_name: my-database-mariadb

    # variables de entorno
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mi_base_de_datos
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword

    # mapeo de puertos
    ports:
      - 3306:3306

    volumes:
      - ./dbdata/mysql:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    restart: always
    container_name: my-database-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: micontrasenia
      MONGO_INITDB_DATABASE: mibasededatos
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017

  servidor:
    # nombre del contendor
    container_name: server-parcial

    # imagen a utilizar
    build:
      # carpeta donde se encuentra el codigo
      context: ./server

      # ubica el dockerfile
      dockerfile: Dockerfile

    # variables de entorno
    environment:
      PORT: 3000
      DATABASE_HOST: mariadb
      DATABASE_USER: root
      DATABASE_PASSWORD: mysecretpassword
      DATABASE_NAME: mi_base_de_datos

      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: micontrasenia
      ME_CONFIG_MONGODB_DATABASE: mibasededatos

    # si falla intenta reiniciarse
    restart: always

    # dependencias del contenedor
    depends_on:
      - mariadb
      - mongodb

    # mapeo de puertos
    ports:
      - 3000:3000

    volumes:
      - ./server:/server
